import Head from "next/head";
import { Box, Heading } from "@chakra-ui/react";
import { Editor } from "@tinymce/tinymce-react";
import { useEffect, useRef, useState } from "react";
export default function Home() {
  const editorRef = useRef(null);
  const [value, setValue] = useState(
    "<p>The quick brown fox jumps over the lazy dog</p>"
  );
  const [text, setText] = useState("");

  function handleEditorChange(e) {
    setContent(e.target.getContent());
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading>React</Heading>

        <Editor
          apiKey="9e6zrt6tjm44ammn80f49rlcqhidyil1q1azncfys7a3f6z1"
          value={value}
          onInit={(evt, editor) => {
            setText(editor.getContent({ format: "text" }));
          }}
          onEditorChange={(newValue, editor) => {
            setValue(newValue);
            setText(editor.getContent({ format: "text" }));
          }}
          plugins={"lists code"}
        />
        {text}
      </Box>
    </>
  );
}
